1) What are the benefits of the built-in array package, if any?


In [1]:
#If the packages are built in we can get benefitted with functions without defining it again and again.
#Performance of the code will be increased.
#Code looks easier to understand.

2) What are some of the array package's limitations?


In [2]:
#The dimensions of array is cannot be changed be later
#Array occupies the memory w.r.to its size independent to the elements stored in the array
#If we want to modify the array it is inefficient to modify the elements

3) Describe the main differences between the array and numpy packages.


In [3]:
#Numpy is used for Scientific computing which creates a multidimensional array object where as array is equivalent to lists
#Numpy consumes less space
#Numpy package performs with greater speed than arrays.
#NUmpy packages is very much optimized for doing all the mathematical calculations and there are built in functions

4) Explain the distinctions between the empty, ones, and zeros functions.


In [4]:
import numpy as np

In [5]:
zeroes=np.zeros([2,2])
zeroes

array([[0., 0.],
       [0., 0.]])

In [6]:
ones=np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [7]:
#Return a new array of given shape and type, without initializing entries.
x=np.empty([2,2],dtype=int)
x

array([[ -706084499, -1481856183],
       [ 1425712495,  -558197219]])

5) In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?


In [8]:
#The function is called with N parameters where N is the rank of shape. 
#Each parameter represents the coordinates of the array varying along a specific axis.
sdf=np.fromfunction(lambda a,b: a+b,(4,4),dtype=float)
print(sdf)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


6) What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?


In [9]:
ones

array([[1., 1.],
       [1., 1.]])

In [10]:
#Each value in the array is added with the scalar
ones+3

array([[4., 4.],
       [4., 4.]])

7)  Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?



In [11]:
#Yes We can do it. Scalar value is added to array with operation assignment 
#array value will be changed
ones+=3

In [12]:
ones

array([[4., 4.],
       [4., 4.]])

8)  Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?



In [13]:
cities=np.array(['Guntur','Vijaywada',""])
cities

array(['Guntur', 'Vijaywada', ''], dtype='<U9')

In [14]:
cities[cities==""]="Vishakapatnam"

In [15]:
cities

array(['Guntur', 'Vijaywada', 'Vishakapa'], dtype='<U9')

In [16]:
#As we can see array has fixed length string.

In [17]:
cities=np.array(['Guntur','Vijaywada',""],dtype='object')
cities

array(['Guntur', 'Vijaywada', ''], dtype=object)

In [18]:
cities[cities==""]="Vishakapatnam"
cities

array(['Guntur', 'Vijaywada', 'Vishakapatnam'], dtype=object)

In [19]:
#We can modify by mentioning dtype as object

9) What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?


In [20]:
ones

array([[4., 4.],
       [4., 4.]])

In [21]:
zeroes

array([[0., 0.],
       [0., 0.]])

In [22]:
ones+zeroes

array([[4., 4.],
       [4., 4.]])

In [23]:
ones*zeroes

array([[0., 0.],
       [0., 0.]])

In [24]:
rand=np.random.rand(2,3)
rand

array([[0.92952788, 0.44951976, 0.3918954 ],
       [0.25512012, 0.58989213, 0.5295437 ]])

In [25]:
#We can perform multiplication with operator because generally we need to follow rules of matrix

10) What is the best way to use a Boolean array to mask another array?


In [26]:
x=np.array([4,5,6,7,8,9])
y=x>6
print(x>6)

[False False False  True  True  True]


In [27]:
y

array([False, False, False,  True,  True,  True])

In [28]:
numbers=x[y==True]
print(numbers)

[7 8 9]


In [29]:
z=np.array([11,12,13,14,15,16])
t=z[x>6]
print(t)

[14 15 16]


11)  What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.


In [30]:
#Direct Method, Short cut method, Step Deviation method are used to find out the Standard deviation

In [31]:
#Generally compute the mean,variance and then standard deviation

In [32]:
np.std(rand,axis=1)

array([0.24101107, 0.14568708])

In [33]:
np.std(t,axis=0)

0.816496580927726

12) What is the dimensionality of a Boolean mask-generated array?


In [34]:
#The dimensionality will be--> where the condition satisfies in the mask and returns the satisfied result.
#Both the arrays should have same length
z=np.array([11,12,13,14,15,16])
t=z[x>6]
print(type(t))
print(t)

<class 'numpy.ndarray'>
[14 15 16]
